# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfoos: 'c2961521-93bc-4efa-97d9-5ec53d9a4f30'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: |
          $(dockerfoos)
        command: buildAndpush
        repository: 'jfrank23/foosstats'
        dockerfile: 'DockerFile'
        tags: |
          $(tag)
          latest